### ISSUE TITLE
Helper function to merge two or more `ErrorCollection`s

### ISSUE THREAD

**Issue by chrishutchinson** [times/error-collection#2]
In the case where we have two or more `ErrorCollection`s, we should provide a helper that merges them together.

**Comment by elliotdavies** [comment]
Ref https://github.com/newsuk/times-components-api/pull/49/files/e8fe7bd2507373b5ab7f5788ceead2397d8cefe5..dc6e1c2def155c940eee6bb02e0de921ab17163f#r116262546
